baseURL: https://www.jschneider.eu/
languageCode: en-uk
title: Home page
paginate: 5
theme: PaperModX

publishDir: docs

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Home page | Jan Thorben Schneider
    description: "This is the personal home page of Jan Thorben Schneider"
    keywords: [Blog, Portfolio, home page]
    author: Jan Thorben Schneider
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "2 January 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: true
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: true
    tocside: 'left'

    assets:
        # disableFingerprinting: true
        favicon: /favicons/favicon.ico
        favicon16x16: /favicons/favicon-16x16.png
        favicon32x32: /favicons/favicon-32x32.png
        favicon48x48: /favicons/favicon-48x48.png
        apple_touch_icon: /favicons/apple-touch-icon.png
        safari_pinned_tab: /favicons/favicon.svg
        favicon_svg: /favicons/favicon.svg





    label:
        text: "Home"
        icon: /favicons/apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Jan Thorben Schneider
        subtitle: "I am a young theoretical physicist"
        imageUrl: images/portrait.jpg
        imageWidth: 150
        imageHeight: 150
        imageTitle: my portrait
        buttons:
            - name: LRXXZ ES rescaling
              url: es-rescaling.html
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    socialIcons:
        - name: twitter
          url: "https://twitter.com/jan_thorben"
        - name: googlescholar
          url: "https://scholar.google.com/citations?user=hsyaTTUAAAAJ"
        - name: github
          url: "https://github.com/jtschneider"
        - name: linkedin
          url: "https://www.linkedin.com/in/jan-schneider-399050103/"
        - name: arxiv
          url: "https://arxiv.org/a/schneider_j_1.html"
        - name: orcid
          url: "https://orcid.org/0000-0001-9854-998X"

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"
    #     bing:
    #         SiteVerificationTag: "XYZabc"
    #     yandex:
    #         SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/jtschneider/jtschneider.github.io/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        # - identifier: categories
        #   name: categories
        #   url: /categories/
        #   weight: 10
        # - identifier: tags
        #   name: tags
        #   url: /tags/
        #   weight: 20
        - identifier: CPHT
          name: "Quinfog website"
          url: https://quinfog.hbar.es/
          weight: 30
          params:
            external: true
# Read: https://github.com/reorx/hugo-PaperModX/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
